spring:
  thymeleaf:
    cache: false

  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  #
  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:test
  #    username: sa
  #    password:
  #
  #  jpa:
  #    hibernate:
  #      ddl-auto: create
  #    show-sql: true

  security:
    oauth2.client:
      registration:
        google:
          client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
          client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
          scope:
            - email
            - profile


logging:
  level:
    root: INFO
    com.example.oauth2proj.*: debug

